on:
  workflow_dispatch
#on: 
#  workflow_dispatch:
#    inputs:
#      logLevel:
#        description: 'Log level'     
#        required: true
#        default: 'warning'
#      tags:
#        description: 'Test GitHub Workflow'
jobs:
  job:
    runs-on: ubuntu-latest
    name: Workflow Job
    steps:
      # Checkout: To use this repository's action, we must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      # Action: Run the action
      - name: Action
        id: action
        uses: ./.github/actions/fetch-json-write-file
        with:
          ap-url: 'http://wedata.net/databases/AutoPagerize/items_all.json'
          ap-file: 'databases/AutoPagerize/items_all.json'
          is-url: 'http://wedata.net/databases/X/items_all.json'
          is-file: 'databases/X/items_all.json'          
      # Commit: Commit the action's file changes (if successful)
      - name: Commit
        if: steps.action.outputs.successful == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "Workflow Action"
          git push
